function output = Delay_Doppler_Channel(SampleRate, KFactor, DopplerFreq, Delays, Power, input)

DopplerSpectrum = doppler('Jakes');

ricChan = comm.RicianChannel( ...
    'SampleRate',              SampleRate, ...
    'PathDelays',              Delays, ...
    'AveragePathGains',        Power, ...
    'KFactor',                 KFactor, ...
    'DirectPathDopplerShift',  -20, ...
    'MaximumDopplerShift',     DopplerFreq, ...
    'DopplerSpectrum',         DopplerSpectrum, ...
    'ChannelFiltering',        true, ...
    'FadingTechnique',         'Sum of sinusoids');

output = ricChan(input');

release(ricChan);

end